import { RunResult } from '../types.js';

const SUPABASE_STORAGE_URL = 'https://pyhdeeryzqmiydawwrjo.supabase.co/storage/v1/object/public/screenshots';

/**
 * Extract the shortId from a share URL like https://codacy-accept.lovable.app/r/sbv78l5
 */
function getShortId(shareUrl: string): string | null {
  const match = shareUrl.match(/\/r\/([a-zA-Z0-9]+)$/);
  return match ? match[1] : null;
}

/**
 * Build the public screenshot URL for a step.
 */
function getScreenshotUrl(shortId: string, stepIndex: number): string {
  return `${SUPABASE_STORAGE_URL}/${shortId}/step-${stepIndex}.png`;
}

export function buildPrComment(result: RunResult): string {
  const { spec, steps, passed, failed, totalDurationMs, commit, shareUrl } = result;
  const total = passed + failed;
  const allPassed = failed === 0;
  const totalSec = (totalDurationMs / 1000).toFixed(1);
  const shortSha = commit ? commit.slice(0, 7) : 'unknown';
  const shortId = shareUrl ? getShortId(shareUrl) : null;

  let md = `## Codacy Accept — Verification Report\n\n`;

  // Spec info
  md += `> **${spec.title}**\n`;
  if (spec.why) {
    md += `> ${spec.why}\n`;
  }
  md += `\n`;

  // Summary table
  md += `| Step | Result | Time |\n`;
  md += `|------|--------|------|\n`;
  for (const s of steps) {
    const icon = s.status === 'passed' ? ':white_check_mark:' : ':x:';
    const sec = (s.durationMs / 1000).toFixed(1);
    md += `| ${s.step.description} | ${icon} | ${sec}s |\n`;
  }
  md += `\n`;

  // Result line
  const resultIcon = allPassed ? ':white_check_mark:' : ':x:';
  md += `${resultIcon} **Result: ${passed}/${total} passed** in ${totalSec}s | Commit: \`${shortSha}\`\n\n`;

  // Cloud link
  if (shareUrl) {
    md += `:link: **[Full Report with Recording & Screenshots](${shareUrl})**\n\n`;
  }

  // Step details with embedded screenshots
  md += `<details>\n<summary>Step Details & Screenshots</summary>\n\n`;
  for (const s of steps) {
    const icon = s.status === 'passed' ? ':white_check_mark:' : ':x:';
    const sec = (s.durationMs / 1000).toFixed(1);
    md += `#### ${icon} Step ${s.step.index}: ${s.step.description} (${sec}s)\n\n`;
    if (s.error) {
      md += `> :x: **Error:** ${s.error}\n\n`;
    }
    if (shortId) {
      const screenshotUrl = getScreenshotUrl(shortId, s.step.index);
      md += `![Step ${s.step.index}: ${s.step.description}](${screenshotUrl})\n\n`;
    }
  }
  md += `</details>\n\n`;

  // Footer
  md += `---\n<sub>Generated by <a href="https://github.com/codacy/codacy-accept">Codacy Accept</a></sub>\n`;

  return md;
}
