import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { RunResult } from '../types.js';

function screenshotToBase64(path: string): string {
  try {
    const buffer = readFileSync(path);
    return buffer.toString('base64');
  } catch {
    return '';
  }
}

export function generateHtmlReport(result: RunResult): string {
  const stepsHtml = result.steps
    .map((s) => {
      const statusClass = s.status === 'passed' ? 'passed' : 'failed';
      const statusIcon = s.status === 'passed' ? '&#x2705;' : '&#x274C;';
      const b64 = screenshotToBase64(s.screenshotPath);
      const imgTag = b64
        ? `<img src="data:image/png;base64,${b64}" alt="Step ${s.step.index} screenshot" />`
        : '<p class="no-screenshot">No screenshot available</p>';
      const errorHtml = s.error
        ? `<div class="error"><strong>Error:</strong> ${escapeHtml(s.error)}</div>`
        : '';
      const diagnosisHtml = '';
      const duration = (s.durationMs / 1000).toFixed(1);

      return `
      <div class="step-card ${statusClass}">
        <div class="step-header">
          <span class="step-icon">${statusIcon}</span>
          <span class="step-num">Step ${s.step.index}</span>
          <span class="step-desc">${escapeHtml(s.step.description)}</span>
          <span class="step-duration">${duration}s</span>
        </div>
        ${errorHtml}
        ${diagnosisHtml}
        <div class="step-screenshot">${imgTag}</div>
      </div>`;
    })
    .join('\n');

  const whyHtml = result.spec.why
    ? `<div class="why-block"><strong>Why:</strong> ${escapeHtml(result.spec.why)}</div>`
    : '';

  const statusBadge =
    result.failed === 0
      ? `<span class="badge badge-pass">${result.passed}/${result.passed} passed</span>`
      : `<span class="badge badge-fail">${result.passed}/${result.passed + result.failed} passed</span>`;

  const commitHtml = result.commit
    ? `<span class="meta-item">Commit: <code>${result.commit.slice(0, 7)}</code></span>`
    : '';

  const totalDuration = (result.totalDurationMs / 1000).toFixed(1);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(result.spec.title)} — Codacy Accept</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8f9fa; color: #1a1a2e; line-height: 1.6; }
  .container { max-width: 900px; margin: 0 auto; padding: 2rem 1rem; }
  .header { margin-bottom: 2rem; }
  .header h1 { font-size: 1.75rem; margin-bottom: 0.5rem; }
  .meta { display: flex; flex-wrap: wrap; gap: 1rem; color: #666; font-size: 0.875rem; margin-bottom: 0.5rem; }
  .meta-item { }
  .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 999px; font-weight: 600; font-size: 0.875rem; }
  .badge-pass { background: #dcfce7; color: #166534; }
  .badge-fail { background: #fee2e2; color: #991b1b; }
  .why-block { background: #fef9c3; border-left: 4px solid #eab308; padding: 1rem 1.25rem; border-radius: 0.5rem; margin-bottom: 2rem; font-size: 1rem; }
  .step-card { background: #fff; border: 1px solid #e5e7eb; border-radius: 0.75rem; margin-bottom: 1.5rem; overflow: hidden; }
  .step-card.failed { border-color: #fca5a5; }
  .step-header { display: flex; align-items: center; gap: 0.75rem; padding: 1rem 1.25rem; border-bottom: 1px solid #e5e7eb; }
  .step-icon { font-size: 1.25rem; }
  .step-num { font-weight: 600; color: #666; font-size: 0.875rem; }
  .step-desc { flex: 1; }
  .step-duration { color: #999; font-size: 0.875rem; }
  .step-screenshot img { width: 100%; display: block; }
  .error { padding: 0.75rem 1.25rem; background: #fef2f2; color: #991b1b; font-size: 0.875rem; }
  .diagnosis { padding: 0.75rem 1.25rem; background: #fffbeb; border-left: 3px solid #f59e0b; color: #92400e; font-size: 0.875rem; }
  .no-screenshot { padding: 2rem; text-align: center; color: #999; }
  .footer { text-align: center; color: #999; font-size: 0.8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; }
  .footer a { color: #666; }
  @media print { body { background: #fff; } .container { padding: 0; } }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>${escapeHtml(result.spec.title)}</h1>
    <div class="meta">
      <span class="meta-item">${escapeHtml(result.spec.url)}</span>
      <span class="meta-item">${new Date(result.timestamp).toLocaleString()}</span>
      ${commitHtml}
      <span class="meta-item">${totalDuration}s total</span>
    </div>
    ${statusBadge}
  </div>

  ${whyHtml}

  ${stepsHtml}

  <div class="footer">
    Generated by <a href="https://codacy.com/accept">Codacy Accept</a>
  </div>
</div>
</body>
</html>`;

  return html;
}

export function saveHtmlReport(result: RunResult): string {
  const html = generateHtmlReport(result);
  const reportPath = join(result.reportPath, 'report.html');
  writeFileSync(reportPath, html);
  return reportPath;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
